apiVersion: apps/v1
kind: Deployment
metadata:
  name: csv-web
  labels:
    app: csv-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: csv-web
  template:
    metadata:
      labels:
        app: csv-web
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: web
          image: "{{ .Values.image.web.repository }}:{{ .Values.image.web.tag }}"
          imagePullPolicy: {{ .Values.image.web.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          # volumeMounts:
          #   - name: shared-storage
          #     mountPath: /shared
          volumeMounts:
            - name: shared-storage
              mountPath: "{{ .Values.persistence.mountPath }}"
        - name: nginx
          image: "{{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag }}"
          imagePullPolicy: {{ .Values.image.nginx.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-storage
              mountPath: /usr/share/nginx/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      # volumes:
      #   - name: shared-storage
      #     persistentVolumeClaim:
      #       claimName: csv-web-pvc
      volumes:
        - name: shared-storage
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: csv-web-nginx-config