apiVersion: v1
kind: Service
metadata:
  name: csv-web
  labels:
    app: csv-web
spec:
  type: {{ .Values.service.type }}
  selector:
    app: csv-web
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80